version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      python-development-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "PyYAML"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: scope
